name: "Generate Documentation and Publish Release"

on:
  workflow_run:
    workflows: ["Synthesis and Results"]  # Must match the name in synth_sta.yml
    types: [completed]

jobs:
  docs-and-release:
    # Only run if the first workflow ended successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      actions: read  # This is needed to download artifacts from other workflows

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts from synthesis workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "Synthesis and Results"
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}

      - name: Extract synthesis results
        run: |
          ls -la
          tar -xzvf synthesis-results.tar.gz
          mkdir -p out
          cp -r artifacts/results out/
          find artifacts -name "*.v" -exec cp {} out/ \;
          ls -la out/results/

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
        
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra

      - name: Remove old table & use \input
        run: |
          SYN_TEX="doc/user-guide/syn.tex"
          SNIPPET_NOEXT="synthResultsSnippet"  # We'll do \include{../../out/results/synthResultsSnippet} (no .tex extension)
          SNIPPET_PATH="out/results/${SNIPPET_NOEXT}.tex"

          if [ -f "$SYN_TEX" ] && [ -f "$SNIPPET_PATH" ]; then
            echo "Backing up $SYN_TEX"
            cp "$SYN_TEX" "$SYN_TEX.bak"

            echo "Removing old static table..."
            sed -i '/\\begin{longtable}/,/\\end{longtable}/d' "$SYN_TEX"

            echo "Inserting a \\input statement in $SYN_TEX"
            # Double backslash so that we end up with a single '\' in the final .tex
            sed -i '/\\rowcolors{2}{gray!30}{gray!10}/a \\\input{../../out/results/synthResultsSnippet}' doc/user-guide/syn.tex

          else
            echo "Missing $SYN_TEX or $SNIPPET_PATH; skipping injection."
          fi

      - name: Build Documentation
        run: |
          nix develop --command make docs

      - name: Collect artifacts
        run: |
          mkdir -p release_artifacts

          # Copy PDF(s) from out/doc
          if [ -d out/doc ]; then
            find out/doc -name "*.pdf" -exec cp {} release_artifacts/ \;
          fi

          # Copy Verilog
          find artifacts -name "*.v" -exec cp {} release_artifacts/ \;

          # Copy JSON + snippet .tex files
          cp -r out/results/* release_artifacts/ || true

          echo "Artifacts in release_artifacts:"
          ls -la release_artifacts

          tar -czvf release_artifacts.tar.gz release_artifacts/

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release_artifacts.tar.gz
            release_artifacts/*.pdf
            release_artifacts/*.v
            release_artifacts/*.json
            release_artifacts/*.tex
          tag_name: v${{ github.run_number }}
          name: "Release ${{ github.run_number }}"
          draft: false
          prerelease: false