name: Synthesis and Results

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  synth-and-publish:
    runs-on: ubuntu-latest
    # Skip on bot commits
    if: ${{ !contains(github.event.head_commit.message, '[gh-bot]') }}

    permissions:
      contents: write  # For committing changes

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Run Synthesis
        run: |
          echo "Running Synthesis..."
          nix develop --command make synth
          echo "Synthesis complete."

      - name: Run Static Timing Analysis
        run: |
          echo "Running STA..."
          nix develop --command make sta
          echo "STA complete."

      - name: Prepare output directory
        run: |
          mkdir -p out/results
          echo "Created out/results directory."

      - name: Parse all config directories
        run: |
          # 1) Initialize a JSON array
          echo "[]" > out/results/synth_results.json

          # 2) Prepare an empty file for LaTeX table rows
          echo "% Auto-generated table rows" > out/results/synth_table_rows.tex

          # 3) Find all config subdirs
          CONFIG_DIRS=$(find out/synth -type d -name "*bits*sync*baud*" | sort)
          if [ -z "$CONFIG_DIRS" ]; then
            echo "Error: No synthesis results found in out/synth"
            exit 1
          fi

          for d in $CONFIG_DIRS; do
            echo "Processing: $d"
            CONFIG_NAME=$(basename "$d")

            # Default placeholders
            GATES="N/A"
            AREA="N/A"
            COMBO_CELLS="N/A"
            SEQ_CELLS="N/A"
            BUF_INV_CELLS="N/A"
            CLOCK_PERIOD="5.0"
            SLACK="0.0"
            CRITICAL_PATH="N/A"
            SETUP_TIME="N/A"
            HOLD_TIME="N/A"
            MAX_FREQ="200.00"

            # gates.txt
            if [ -f "$d/gates.txt" ]; then
              GATES=$(cat "$d/gates.txt")
            fi

            # log.txt for area, cells, timing
            if [ -f "$d/log.txt" ]; then
              AREA=$(grep "Chip area" "$d/log.txt" | awk '{print $5}' || echo "N/A")
              COMBO_CELLS=$(grep "Combinational cells:" "$d/log.txt" | awk '{print $3}' || echo "N/A")
              SEQ_CELLS=$(grep "Sequential cells:" "$d/log.txt" | awk '{print $3}' || echo "N/A")
              BUF_INV_CELLS=$(grep "Buf/Inv cells:" "$d/log.txt" | awk '{print $3}' || echo "N/A")

              tmp_clock=$(grep "Clock period:" "$d/log.txt" | awk '{print $3}')
              tmp_slack=$(grep "Slack:" "$d/log.txt" | head -1 | awk '{print $2}')
              tmp_cp=$(grep -A 1 "Critical path" "$d/log.txt" | grep -v "Critical path" | head -1 | tr -s ' ' | cut -d' ' -f2-)
              tmp_setup=$(grep "Setup time:" "$d/log.txt" | awk '{print $3}')
              tmp_hold=$(grep "Hold time:" "$d/log.txt" | awk '{print $3}')

              [ -n "$tmp_clock" ] && CLOCK_PERIOD=$tmp_clock
              [ -n "$tmp_slack" ] && SLACK=$tmp_slack
              [ -n "$tmp_cp" ] && CRITICAL_PATH=$tmp_cp
              [ -n "$tmp_setup" ] && SETUP_TIME=$tmp_setup
              [ -n "$tmp_hold" ] && HOLD_TIME=$tmp_hold

              freq_calc=$(awk "BEGIN {print 1000/$CLOCK_PERIOD}" 2>/dev/null)
              [ -n "$freq_calc" ] && MAX_FREQ=$(printf "%.2f" "$freq_calc")
            fi

            # Slack >= 0 => pass
            STA_PASSES="Yes"
            SLACK_SIGN=$(awk "BEGIN {print ($SLACK < 0) ? 1 : 0}")
            if [ "$SLACK_SIGN" -eq 1 ]; then
              STA_PASSES="No"
            fi

            # Attempt to parse e.g. 8bits, 2sync, 900000baud from directory name
            DATA_BITS=$(echo "$CONFIG_NAME" | grep -oE '^[0-9]+bits' | sed 's/bits//')
            FIFO_DEPTH=$(echo "$CONFIG_NAME" | grep -oE '_[0-9]+sync_' | tr -dc '0-9')
            BAUD=$(echo "$CONFIG_NAME" | grep -oE '[0-9]+baud' | sed 's/baud//')

            DATA_BITS="${DATA_BITS:-N/A}"
            FIFO_DEPTH="${FIFO_DEPTH:-N/A}"
            BAUD="${BAUD:-N/A}"

            # Construct a JSON object
            newObj=$(jq -n \
              --arg cfg "$CONFIG_NAME" \
              --arg gates "$GATES" \
              --arg area "$AREA" \
              --arg combo "$COMBO_CELLS" \
              --arg seq "$SEQ_CELLS" \
              --arg buf "$BUF_INV_CELLS" \
              --arg bits "$DATA_BITS" \
              --arg depth "$FIFO_DEPTH" \
              --arg bd "$BAUD" \
              --arg cper "$CLOCK_PERIOD" \
              --arg slk "$SLACK" \
              --arg cpath "$CRITICAL_PATH" \
              --arg stime "$SETUP_TIME" \
              --arg htime "$HOLD_TIME" \
              --arg freq "$MAX_FREQ" \
              --arg pass "$STA_PASSES" \
              '{
                config_name: $cfg,
                gates: $gates,
                area: $area,
                combinational_cells: $combo,
                sequential_cells: $seq,
                buffer_inverter_cells: $buf,
                data_bits: $bits,
                fifo_depth: $depth,
                baud: $bd,
                timing: {
                  clock_period: $cper,
                  slack: $slk,
                  critical_path: $cpath,
                  setup_time: $stime,
                  hold_time: $htime,
                  max_frequency_mhz: $freq,
                  sta_passes: $pass
                }
              }'
            )

            tmp_file=$(mktemp)
            jq ". + [ $newObj ]" out/results/synth_results.json > "$tmp_file"
            mv "$tmp_file" out/results/synth_results.json

            # Append a row to the table snippet
            echo "\\texttt{$CONFIG_NAME} & $FIFO_DEPTH & $DATA_BITS & $GATES \\\\ \\hline" >> out/results/synth_table_rows.tex
          done

          # Build out/results/synth_results.tex line by line (to avoid heredocs)
          echo "% Auto-generated table of all configs" > out/results/synth_results.tex
          echo "\\renewcommand*{\\arraystretch}{1.3}" >> out/results/synth_results.tex
          echo "\\rowcolors{2}{gray!30}{gray!10}" >> out/results/synth_results.tex
          echo "\\begin{longtable}[H]{| p{0.22\\textwidth} | p{0.18\\textwidth} | p{0.20\\textwidth} | p{0.30\\textwidth} |}" >> out/results/synth_results.tex
          echo "\\hline" >> out/results/synth_results.tex
          echo "\\rowcolor{gray}" >> out/results/synth_results.tex
          echo "\\textcolor{white}{\\textbf{Config}} &" >> out/results/synth_results.tex
          echo "\\textcolor{white}{\\textbf{FIFO Depth}} &" >> out/results/synth_results.tex
          echo "\\textcolor{white}{\\textbf{Data Bits}} &" >> out/results/synth_results.tex
          echo "\\textcolor{white}{\\textbf{Gate Count}} \\\\ \\hline" >> out/results/synth_results.tex
          echo "\\endfirsthead" >> out/results/synth_results.tex
          echo "" >> out/results/synth_results.tex
          echo "\\hline" >> out/results/synth_results.tex
          echo "\\rowcolor{gray}" >> out/results/synth_results.tex
          echo "\\textcolor{white}{\\textbf{Config}} &" >> out/results/synth_results.tex
          echo "\\textcolor{white}{\\textbf{FIFO Depth}} &" >> out/results/synth_results.tex
          echo "\\textcolor{white}{\\textbf{Data Bits}} &" >> out/results/synth_results.tex
          echo "\\textcolor{white}{\\textbf{Gate Count}} \\\\ \\hline" >> out/results/synth_results.tex
          echo "\\endhead" >> out/results/synth_results.tex
          echo "" >> out/results/synth_results.tex
          echo "\\hline" >> out/results/synth_results.tex
          echo "\\endfoot" >> out/results/synth_results.tex

          cat out/results/synth_table_rows.tex >> out/results/synth_results.tex
          echo "\\caption{Synthesis Results for All Configs}" >> out/results/synth_results.tex
          echo "\\end{longtable}" >> out/results/synth_results.tex

      - name: Generate Verilog
        run: |
          echo "Generating Verilog..."
          nix develop --command make verilog
          echo "Verilog generation complete."

      - name: Commit results
        run: |
          echo "Configuring git..."
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          echo "Staging out/results..."
          git add --force out/results

          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            echo "Committing results..."
            git commit -m "[gh-bot] Update synthesis/STA results"
            git pull --rebase origin main
            git push origin main
          fi
